<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\post\\backends\\mailbackend' => '/Backends/Wrappers/MailBackend.php',
                'ganked\\post\\bootstrapper' => '/Bootstrapper.php',
                'ganked\\post\\commands\\authenticationcommand' => '/Commands/AuthenticationCommand.php',
                'ganked\\post\\commands\\connectsteamaccounttousercommand' => '/Commands/ConnectSteamAccountToUserCommand.php',
                'ganked\\post\\commands\\createnewpostcommand' => '/Commands/Social/CreateNewPostCommand.php',
                'ganked\\post\\commands\\favouritesummonercommand' => '/Commands/LeagueOfLegends/FavouriteSummonerCommand.php',
                'ganked\\post\\commands\\insertsteamusercommand' => '/Commands/InsertSteamUserCommand.php',
                'ganked\\post\\commands\\insertusercommand' => '/Commands/InsertUserCommand.php',
                'ganked\\post\\commands\\loginusercommand' => '/Commands/LoginUserCommand.php',
                'ganked\\post\\commands\\removesteamidfromsessioncommand' => '/Commands/RemoveSteamIdFromSessionCommand.php',
                'ganked\\post\\commands\\unfavouritesummonercommand' => '/Commands/LeagueOfLegends/UnfavouriteSummonerCommand.php',
                'ganked\\post\\commands\\unlocksessionfromsteamlogincommand' => '/Commands/UnlockSessionFromSteamLoginCommand.php',
                'ganked\\post\\commands\\updateuserhashcommand' => '/Commands/UpdateUserHashCommand.php',
                'ganked\\post\\commands\\updateuserpasswordcommand' => '/Commands/UpdateUserPasswordCommand.php',
                'ganked\\post\\commands\\verifyusercommand' => '/Commands/VerifyUserCommand.php',
                'ganked\\post\\controllers\\postcontroller' => '/Controllers/PostController.php',
                'ganked\\post\\factories\\backendfactory' => '/Factories/BackendFactory.php',
                'ganked\\post\\factories\\commandfactory' => '/Factories/CommandFactory.php',
                'ganked\\post\\factories\\controllerfactory' => '/Factories/ControllerFactory.php',
                'ganked\\post\\factories\\handlerfactory' => '/Factories/HandlerFactory.php',
                'ganked\\post\\factories\\mailfactory' => '/Factories/MailFactory.php',
                'ganked\\post\\factories\\queryfactory' => '/Factories/QueryFactory.php',
                'ganked\\post\\factories\\routerfactory' => '/Factories/RouterFactory.php',
                'ganked\\post\\handlers\\abstracthandler' => '/Handlers/AbstractHandler.php',
                'ganked\\post\\handlers\\handlerinterface' => '/Handlers/HandlerInterface.php',
                'ganked\\post\\handlers\\redirect\\abstractredirecthandler' => '/Handlers/Redirect/AbstractRedirectHandler.php',
                'ganked\\post\\handlers\\redirect\\addsteamaccountredirecthandler' => '/Handlers/Redirect/AddSteamAccountRedirectHandler.php',
                'ganked\\post\\handlers\\redirect\\logoutredirecthandler' => '/Handlers/Redirect/LogoutRedirectHandler.php',
                'ganked\\post\\handlers\\redirect\\resendverificationmailredirecthandler' => '/Handlers/Redirect/ResendVerificationMailRedirectHandler.php',
                'ganked\\post\\handlers\\redirect\\steamloginredirecthandler' => '/Handlers/Redirect/SteamLoginRedirectHandler.php',
                'ganked\\post\\handlers\\redirect\\verificationredirecthandler' => '/Handlers/Redirect/VerificationRedirectHandler.php',
                'ganked\\post\\handlers\\request\\abstractrequesthandler' => '/Handlers/Request/AbstractRequestHandler.php',
                'ganked\\post\\handlers\\request\\createnewpostrequesthandler' => '/Handlers/Request/Social/CreateNewPostRequestHandler.php',
                'ganked\\post\\handlers\\request\\forgotpasswordmailrequesthandler' => '/Handlers/Request/ForgotPasswordMailRequestHandler.php',
                'ganked\\post\\handlers\\request\\loginrequesthandler' => '/Handlers/Request/LoginRequestHandler.php',
                'ganked\\post\\handlers\\request\\passwordrecoveryrequesthandler' => '/Handlers/Request/PasswordRecoveryRequestHandler.php',
                'ganked\\post\\handlers\\request\\registrationrequesthandler' => '/Handlers/Request/RegistrationRequestHandler.php',
                'ganked\\post\\handlers\\request\\steamregistrationrequesthandler' => '/Handlers/Request/SteamRegistrationRequestHandler.php',
                'ganked\\post\\handlers\\request\\summonerfavouritehandler' => '/Handlers/Request/LeagueOfLegends/SummonerFavouriteHandler.php',
                'ganked\\post\\handlers\\request\\summonerunfavouritehandler' => '/Handlers/Request/LeagueOfLegends/SummonerUnfavouriteHandler.php',
                'ganked\\post\\mails\\abstractmail' => '/Mails/AbstractMail.php',
                'ganked\\post\\mails\\forgotpasswordmail' => '/Mails/ForgotPasswordMail.php',
                'ganked\\post\\mails\\verifymail' => '/Mails/VerifyMail.php',
                'ganked\\post\\models\\jsonmodel' => '/Models/JsonModel.php',
                'ganked\\post\\queries\\hasbetarequestquery' => '/Queries/HasBetaRequestQuery.php',
                'ganked\\post\\queries\\isverifiedforbetaquery' => '/Queries/IsVerifiedForBetaQuery.php',
                'ganked\\post\\routers\\postrequestrouter' => '/Routers/PostRequestRouter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
