<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\api\\commands\\deleteaccesstokencommandtest' => '/unit/Commands/DeleteAccessTokenCommandTest.php',
                'ganked\\api\\commands\\likepostcommandtest' => '/unit/Commands/LikePostCommandTest.php',
                'ganked\\api\\commands\\saveaccesstokencommandtest' => '/unit/Commands/SaveAccessTokenCommandTest.php',
                'ganked\\api\\controllers\\errorcontrollertest' => '/unit/Controller/ErrorControllerTest.php',
                'ganked\\api\\controllers\\getcontrollertest' => '/unit/Controller/GetControllerTest.php',
                'ganked\\api\\factories\\backendfactorytest' => '/unit/Factories/BackendFactoryTest.php',
                'ganked\\api\\factories\\commandfactorytest' => '/unit/Factories/CommandFactoryTest.php',
                'ganked\\api\\factories\\controllerfactorytest' => '/unit/Factories/ControllerFactoryTest.php',
                'ganked\\api\\factories\\genericfactorytesthelper' => '/unit/Factories/GenericFactoryTestHelper.php',
                'ganked\\api\\factories\\handlerfactorytest' => '/unit/Factories/HandlerFactoryTest.php',
                'ganked\\api\\factories\\queryfactorytest' => '/unit/Factories/QueryFactoryTest.php',
                'ganked\\api\\factories\\readerfactorytest' => '/unit/Factories/ReaderFactoryTest.php',
                'ganked\\api\\factories\\routerfactorytest' => '/unit/Factories/RouterFactoryTest.php',
                'ganked\\api\\factories\\servicefactorytest' => '/unit/Factories/ServiceFactoryTest.php',
                'ganked\\api\\handlers\\delete\\accesstoken\\commandhandlertest' => '/unit/Handlers/Delete/AccessToken/CommandHandlerTest.php',
                'ganked\\api\\handlers\\get\\posts\\queryhandlertest' => '/unit/Handlers/Get/Posts/QueryHandlerTest.php',
                'ganked\\api\\handlers\\get\\users\\likes\\queryhandlertest' => '/unit/Handlers/Get/Users/Likes/QueryHandlerTest.php',
                'ganked\\api\\handlers\\get\\users\\posts\\queryhandlertest' => '/unit/Handlers/Get/Users/Posts/QueryHandlerTest.php',
                'ganked\\api\\handlers\\get\\users\\queryhandlertest' => '/unit/Handlers/Get/Users/QueryHandlerTest.php',
                'ganked\\api\\handlers\\get\\users\\responsehandlertest' => '/unit/Handlers/Get/Users/ResponseHandlerTest.php',
                'ganked\\api\\handlers\\post\\accesstoken\\commandhandlertest' => '/unit/Handlers/Post/AccessToken/CommandHandlerTest.php',
                'ganked\\api\\handlers\\post\\posts\\likes\\commandhandlertest' => '/unit/Handlers/Post/Posts/Likes/CommandHandlerTest.php',
                'ganked\\api\\handlers\\post\\posts\\likes\\queryhandlertest' => '/unit/Handlers/Post/Posts/Likes/QueryHandlerTest.php',
                'ganked\\api\\handlers\\post\\posts\\queryhandlertest' => '/unit/Handlers/Post/Posts/QueryHandlerTest.php',
                'ganked\\api\\handlers\\prehandlertest' => '/unit/Handlers/PreHandlerTest.php',
                'ganked\\api\\models\\apimodeltest' => '/unit/Models/ApiModelTest.php',
                'ganked\\api\\models\\apipostmodeltest' => '/unit/Models/ApiPostModelTest.php',
                'ganked\\api\\parsers\\postparsertest' => '/unit/Parsers/PostParserTest.php',
                'ganked\\api\\queries\\fetchpostsbyidsquerytest' => '/unit/Queries/FetchPostsByIdsQueryTest.php',
                'ganked\\api\\queries\\fetchuseridforaccesstokenquerytest' => '/unit/Queries/FetchUserIdForAccessTokenQueryTest.php',
                'ganked\\api\\queries\\fetchuserlikesfromredisquerytest' => '/unit/Queries/FetchUserLikesFromRedisQueryTest.php',
                'ganked\\api\\queries\\getpostbyidquerytest' => '/unit/Queries/GetPostByIdQueryTest.php',
                'ganked\\api\\queries\\getpostsforuserquerytest' => '/unit/Queries/GetPostsForUserQueryTest.php',
                'ganked\\api\\queries\\getuserfromdatabasequerytest' => '/unit/Queries/GetUserFromDatabaseQueryTest.php',
                'ganked\\api\\queries\\haspostbyidquerytest' => '/unit/Queries/HasPostByIdQueryTest.php',
                'ganked\\api\\queries\\hasuserbyidquerytest' => '/unit/Queries/HasUserByIdQueryTest.php',
                'ganked\\api\\readers\\tokenreadertest' => '/unit/Readers/TokenReaderTest.php',
                'ganked\\api\\routers\\deleterequestroutertest' => '/unit/Routers/DeleteRequestRouterTest.php',
                'ganked\\api\\routers\\genericroutertesthelper' => '/unit/Routers/GenericRouterTestHelper.php',
                'ganked\\api\\routers\\getrequestroutertest' => '/unit/Routers/GetRequestRouterTest.php',
                'ganked\\api\\routers\\postrequestroutertest' => '/unit/Routers/PostRequestRouterTest.php',
                'ganked\\api\\services\\postsservicetest' => '/unit/Services/PostsServiceTest.php',
                'ganked\\api\\services\\userservicetest' => '/unit/Services/UserServiceTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
