<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\services\\backends\\slackbackend' => '/Backends/SlackBackend.php',
                'ganked\\services\\bootstrapper' => '/Bootstrapper.php',
                'ganked\\services\\controllers\\serviceclientcontroller' => '/Controllers/ServiceClientController.php',
                'ganked\\services\\controllers\\slackcontroller' => '/Controllers/SlackController.php',
                'ganked\\services\\factories\\backendfactory' => '/Factories/BackendFactory.php',
                'ganked\\services\\factories\\controllerfactory' => '/Factories/ControllerFactory.php',
                'ganked\\services\\factories\\routerfactory' => '/Factories/RouterFactory.php',
                'ganked\\services\\factories\\serviceclientfactory' => '/Factories/ServiceClientFactory.php',
                'ganked\\services\\models\\servicemodel' => '/Models/ServiceModel.php',
                'ganked\\services\\routers\\servicerouter' => '/Routers/ServiceRouter.php',
                'ganked\\services\\serviceclients\\abstractserviceclient' => '/ServiceClients/AbstractServiceClient.php',
                'ganked\\services\\serviceclients\\account\\accountserviceclient' => '/ServiceClients/Account/AccountServiceClient.php',
                'ganked\\services\\serviceclients\\api\\abstractsteamserviceclient' => '/ServiceClients/API/Steam/AbstractSteamServiceClient.php',
                'ganked\\services\\serviceclients\\api\\counterstrikeserviceclient' => '/ServiceClients/API/Steam/CounterStrikeServiceClient.php',
                'ganked\\services\\serviceclients\\api\\dotaserviceclient' => '/ServiceClients/API/Steam/DotaServiceClient.php',
                'ganked\\services\\serviceclients\\api\\lolserviceclient' => '/ServiceClients/API/LoLServiceClient.php',
                'ganked\\services\\serviceclients\\api\\steamserviceclient' => '/ServiceClients/API/Steam/SteamServiceClient.php',
                'ganked\\services\\serviceclients\\api\\twitchserviceclient' => '/ServiceClients/API/TwitchServiceClient.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
