<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\skeleton\\backends\\wrappers\\curlresponsetest' => '/Backends/Wrappers/CurlResponseTest.php',
                'ganked\\skeleton\\backends\\wrappers\\curltest' => '/Backends/Wrappers/CurlTest.php',
                'ganked\\skeleton\\commands\\destroysessioncommandtest' => '/Commands/DestroySessionCommandTest.php',
                'ganked\\skeleton\\commands\\removeuserfromsessioncommandtest' => '/Commands/RemoveUserFromSessionCommandTest.php',
                'ganked\\skeleton\\commands\\storepreviousuricommandtest' => '/Commands/StorePreviousUriCommandTest.php',
                'ganked\\skeleton\\commands\\writesessioncommandtest' => '/Commands/WriteSessionCommandTest.php',
                'ganked\\skeleton\\configurationtest' => '/ConfigurationTest.php',
                'ganked\\skeleton\\controllers\\jsonerrorpagecontrollertest' => '/Controllers/JsonErrorControllerTest.php',
                'ganked\\skeleton\\factories\\applicationfactorytest' => '/Factories/ApplicationFactoryTest.php',
                'ganked\\skeleton\\factories\\backendfactorytest' => '/Factories/BackendFactoryTest.php',
                'ganked\\skeleton\\factories\\commandfactorytest' => '/Factories/CommandFactoryTest.php',
                'ganked\\skeleton\\factories\\controllerfactorytest' => '/Factories/ControllerFactoryTest.php',
                'ganked\\skeleton\\factories\\gatewayfactorytest' => '/Factories/GatewayFactoryTest.php',
                'ganked\\skeleton\\factories\\genericfactorytesthelper' => '/Factories/GenericFactoryTestHelper.php',
                'ganked\\skeleton\\factories\\loggerfactorytest' => '/Factories/LoggerFactoryTest.php',
                'ganked\\skeleton\\factories\\masterfactorytest' => '/Factories/MasterFactoryTest.php',
                'ganked\\skeleton\\factories\\queryfactorytest' => '/Factories/QueryFactoryTest.php',
                'ganked\\skeleton\\factories\\rendererfactorytest' => '/Factories/RendererFactoryTest.php',
                'ganked\\skeleton\\factories\\routerfactorytest' => '/Factories/RouterFactoryTest.php',
                'ganked\\skeleton\\factories\\sessionfactorytest' => '/Factories/SessionFactoryTest.php',
                'ganked\\skeleton\\factories\\transformationfactorytest' => '/Factories/TransformationFactoryTest.php',
                'ganked\\skeleton\\http\\request\\postrequesttest' => '/Http/Request/PostRequestTest.php',
                'ganked\\skeleton\\http\\response\\htmlresponsetest' => '/Http/Response/HtmlResponseTest.php',
                'ganked\\skeleton\\maptest' => '/MapTest.php',
                'ganked\\skeleton\\models\\jsonerrorpagemodeltest' => '/Models/JsonErrorPageModelTest.php',
                'ganked\\skeleton\\queries\\fetchpreviousuriquerytest' => '/Queries/FetchPreviousUriQueryTest.php',
                'ganked\\skeleton\\queries\\fetchsessioncookiequerytest' => '/Queries/FetchSessionCookieQueryTest.php',
                'ganked\\skeleton\\queries\\fetchuserfromsessionquerytest' => '/Queries/FetchUserFromSessionQueryTest.php',
                'ganked\\skeleton\\queries\\fetchuserhashquerytest' => '/Queries/FetchUserHashQueryTest.php',
                'ganked\\skeleton\\queries\\getdomfromfilequerytest' => '/Queries/GetDomFromFileQueryTest.php',
                'ganked\\skeleton\\queries\\issessionstartedquerytest' => '/Queries/IsSessionStartedQueryTest.php',
                'ganked\\skeleton\\queries\\sessionhasuserquerytest' => '/Queries/SessionHasUserQueryTest.php',
                'ganked\\skeleton\\renderers\\xslrenderertest' => '/Renderers/XslRendererTest.php',
                'ganked\\skeleton\\routers\\genericroutertesthelper' => '/Routers/GenericRouterTestHelper.php',
                'ganked\\skeleton\\routers\\jsonerrorroutertest' => '/Routers/JsonErrorRouterTest.php',
                'ganked\\skeleton\\routers\\routertest' => '/Routers/RouterTest.php',
                'ganked\\skeleton\\session\\sessiondatapooltest' => '/Session/SessionDataPoolTest.php',
                'ganked\\skeleton\\session\\sessiontest' => '/Session/SessionTest.php',
                'ganked\\skeleton\\transformations\\snippettransformationtest' => '/Transformations/SnippetTransformationTest.php',
                'ganked\\skeleton\\transformations\\texttransformationtest' => '/Transformations/TextTransformationTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
