<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\backend\\backends\\stream\\pagesstreamwrapper' => '/Backends/Stream/PagesStreamWrapper.php',
                'ganked\\backend\\bootstrapper' => '/Bootstrapper.php',
                'ganked\\backend\\builders\\championpagebuilder' => '/Builders/ChampionPageBuilder.php',
                'ganked\\backend\\builders\\championspagebuilder' => '/Builders/ChampionsPageBuilder.php',
                'ganked\\backend\\builders\\counterstrikeachievementstemplatebuilder' => '/Builders/CounterStrikeAchievementsTemplateBuilder.php',
                'ganked\\backend\\builders\\leagueoflegendsmasteriestemplatebuilder' => '/Builders/LeagueOfLegendsMasteriesTemplateBuilder.php',
                'ganked\\backend\\builders\\staticpagebuilder' => '/Builders/StaticPageBuilder.php',
                'ganked\\backend\\controller' => '/Controller.php',
                'ganked\\backend\\factories\\backendfactory' => '/Factories/BackendFactory.php',
                'ganked\\backend\\factories\\builderfactory' => '/Factories/BuilderFactory.php',
                'ganked\\backend\\factories\\locatorfactory' => '/Factories/LocatorFactory.php',
                'ganked\\backend\\factories\\mapperfactory' => '/Factories/MapperFactory.php',
                'ganked\\backend\\factories\\rendererfactory' => '/Factories/RendererFactory.php',
                'ganked\\backend\\factories\\taskfactory' => '/Factories/TaskFactory.php',
                'ganked\\backend\\factories\\writerfactory' => '/Factories/WriterFactory.php',
                'ganked\\backend\\locators\\rendererlocator' => '/Locators/RendererLocator.php',
                'ganked\\backend\\locators\\tasklocator' => '/Locators/TaskLocator.php',
                'ganked\\backend\\mappers\\leagueoflegendsleaderboardmapper' => '/Mappers/LeagueOfLegendsLeaderboardMapper.php',
                'ganked\\backend\\renderers\\breadcrumbsrenderer' => '/Renderers/BreadcrumbsRenderer.php',
                'ganked\\backend\\renderers\\leagueoflegendsfreechampionsrenderer' => '/Renderers/LeagueOfLegendsFreeChampionsRenderer.php',
                'ganked\\backend\\renderers\\rssfeedsrenderer' => '/Renderers/RssFeedsRenderer.php',
                'ganked\\backend\\request' => '/Request.php',
                'ganked\\backend\\staticpages\\staticpage' => '/StaticPages/StaticPage.php',
                'ganked\\backend\\tasks\\buildchampionpagestask' => '/Tasks/BuildChampionPagesTask.php',
                'ganked\\backend\\tasks\\buildstaticpagetask' => '/Tasks/BuildStaticPageTask.php',
                'ganked\\backend\\tasks\\counterstrikeachievementstemplatebuildtask' => '/Tasks/Build/CounterStrikeAchievementsTemplateBuildTask.php',
                'ganked\\backend\\tasks\\initialtask' => '/Tasks/InitialTask.php',
                'ganked\\backend\\tasks\\leagueoflegendschallengerleaderboardsgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsChallengerLeaderboardsGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendschampionsgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsChampionsGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendscurrentpatchgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsCurrentPatchGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendsfreechampionspushtask' => '/Tasks/Push/LeagueOfLegends/LeagueOfLegendsFreeChampionsPushTask.php',
                'ganked\\backend\\tasks\\leagueoflegendsitemsgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsItemsGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendsmasteriestemplatebuildtask' => '/Tasks/Build/LeagueOfLegendsMasteriesTemplateBuildTask.php',
                'ganked\\backend\\tasks\\leagueoflegendsmasterleaderboardsgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsMasterLeaderboardsGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendsrunesgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsRunesGetTask.php',
                'ganked\\backend\\tasks\\leagueoflegendssummonerspellsgettask' => '/Tasks/Get/LeagueOfLegends/LeagueOfLegendsSummonerSpellsGetTask.php',
                'ganked\\backend\\tasks\\rssfeedsgettask' => '/Tasks/Get/RssFeedsGetTask.php',
                'ganked\\backend\\tasks\\taskinterface' => '/Tasks/TaskInterface.php',
                'ganked\\backend\\writers\\leagueoflegendsleaderboardwriter' => '/Writers/LeagueOfLegendsLeaderboardWriter.php',
                'ganked\\backend\\writers\\staticpagewriter' => '/Writers/StaticPageWriter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
