<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\fetch\\bootstrapper' => '/Bootstrapper.php',
                'ganked\\fetch\\controllers\\datafetchcontroller' => '/Controllers/DataFetchController.php',
                'ganked\\fetch\\factories\\controllerfactory' => '/Factories/ControllerFactory.php',
                'ganked\\fetch\\factories\\handlerfactory' => '/Factories/HandlerFactory.php',
                'ganked\\fetch\\factories\\mapperfactory' => '/Factories/MapperFactory.php',
                'ganked\\fetch\\factories\\queryfactory' => '/Factories/QueryFactory.php',
                'ganked\\fetch\\factories\\routerfactory' => '/Factories/RouterFactory.php',
                'ganked\\fetch\\handlers\\datafetch\\datafetchhandlerinterface' => '/Handlers/DataFetch/DataFetchHandlerInterface.php',
                'ganked\\fetch\\handlers\\datafetch\\landingpagestreamdatafetchhandler' => '/Handlers/DataFetch/LandingPageStreamDataFetchHandler.php',
                'ganked\\fetch\\handlers\\datafetch\\leagueoflegendsmatchdatafetchhandler' => '/Handlers/DataFetch/LeagueOfLegendsMatchDataFetchHandler.php',
                'ganked\\fetch\\handlers\\handlerinterface' => '/Handlers/HandlerInterface.php',
                'ganked\\fetch\\mappers\\landingpagestreammapper' => '/Mappers/LandingPageStreamMapper.php',
                'ganked\\fetch\\queries\\fetchtwitchtopstreamsquery' => '/Queries/FetchTwitchTopStreamsQuery.php',
                'ganked\\fetch\\queries\\queryinterface' => '/Queries/QueryInterface.php',
                'ganked\\fetch\\routers\\datafetchrouter' => '/Routers/DataFetchRouter.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
