# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'lib/lovely_box'

LovelyBox.root = __dir__
LovelyBox.ensure_user_config
lovely_conf = LovelyBox::Config.get :local

Vagrant.configure(2) do |config|
  config.vm.box = 'bento/centos-7.1'
  config.vm.box_check_update = false
  config.vm.hostname = lovely_conf['hostname']

  #
  # Synced Folders
  #
  if lovely_conf['provisioned']
	config.vm.synced_folder '../', '/var/www', create: true, owner: 'nginx',  group: 'nginx', mount_options: ['dmode=775', 'fmode=775']

    config.vm.synced_folder 'conf/php/php-fpm.d', '/etc/php/php-fpm.d', create: true, owner: 'nginx',  group: 'nginx'
  end

  config.vm.synced_folder 'conf/nginx', '/etc/nginx', create: true
  config.vm.synced_folder '.', '/opt/lovelybox', create: true
  config.vm.synced_folder 'conf/elasticsearch', '/etc/elasticsearch', create: true

  #
  # Networking
  #
  config.vm.network :private_network, ip: lovely_conf['network']['private_ip']

  if lovely_conf['network']['public_ip']
    config.vm.network :public_network, ip: lovely_conf['network']['public_ip']
  end

  #
  # Provisioners
  #
  config.vm.provision :shell, path: 'bin/provision', privileged: true
  config.vm.provision :shell, path: 'bin/boot', privileged: true, run: :always
  
  # Source: http://stackoverflow.com/questions/20194128/vagrant-crashes-depending-on-physical-network
  config.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
	  #vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/var_www", "1"]
	  #vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
end
