<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\post\\backends\\mailbackendtest' => '/unit/Backends/Wrappers/MailBackendTest.php',
                'ganked\\post\\commands\\createnewpostcommandtest' => '/unit/Commands/Social/CreateNewPostCommandTest.php',
                'ganked\\post\\commands\\insertusercommandtest' => '/unit/Commands/InsertUserCommandTest.php',
                'ganked\\post\\commands\\loginusercommandtest' => '/unit/Commands/LoginUserCommandTest.php',
                'ganked\\post\\commands\\updateuserhashcommandtest' => '/unit/Commands/UpdateUserHashCommandTest.php',
                'ganked\\post\\commands\\updateuserpasswordcommandtest' => '/unit/Commands/UpdateUserPasswordCommandTest.php',
                'ganked\\post\\commands\\verifyusercommandtest' => '/unit/Commands/VerifyUserCommandTest.php',
                'ganked\\post\\controllers\\postcontrollertest' => '/unit/Controllers/PostControllerTest.php',
                'ganked\\post\\factories\\backendfactorytest' => '/unit/Factories/BackendFactoryTest.php',
                'ganked\\post\\factories\\commandfactorytest' => '/unit/Factories/CommandFactoryTest.php',
                'ganked\\post\\factories\\controllerfactorytest' => '/unit/Factories/ControllerFactoryTest.php',
                'ganked\\post\\factories\\genericfactorytesthelper' => '/unit/Factories/GenericFactoryTestHelper.php',
                'ganked\\post\\factories\\handlerfactorytest' => '/unit/Factories/HandlerFactoryTest.php',
                'ganked\\post\\factories\\mailfactorytest' => '/unit/Factories/MailFactoryTest.php',
                'ganked\\post\\factories\\queryfactorytest' => '/unit/Factories/QueryFactoryTest.php',
                'ganked\\post\\factories\\routerfactorytest' => '/unit/Factories/RouterFactoryTest.php',
                'ganked\\post\\handlers\\redirect\\logoutredirecthandlertest' => '/unit/Handlers/Redirect/LogoutRedirectHandlerTest.php',
                'ganked\\post\\handlers\\redirect\\resendverificationmailredirecthandlertest' => '/unit/Handlers/Redirect/ResendVerificationMailRedirectHandlerTest.php',
                'ganked\\post\\handlers\\redirect\\verificationredirecthandlertest' => '/unit/Handlers/Redirect/VerificationRedirectHandlerTest.php',
                'ganked\\post\\handlers\\request\\createnewpostrequesthandlertest' => '/unit/Handlers/Request/Social/CreateNewPostRequestHandlerTest.php',
                'ganked\\post\\handlers\\request\\forgotpasswordmailrequesthandlertest' => '/unit/Handlers/Request/ForgotPasswordMailRequestHandlerTest.php',
                'ganked\\post\\handlers\\request\\loginrequesthandlertest' => '/unit/Handlers/Request/LoginRequestHandlerTest.php',
                'ganked\\post\\handlers\\request\\passwordrecoveryrequesthandlertest' => '/unit/Handlers/Request/PasswordRecoveryRequestHandlerTest.php',
                'ganked\\post\\handlers\\request\\registrationrequesthandlertest' => '/unit/Handlers/Request/RegistrationRequestHandlerTest.php',
                'ganked\\post\\mails\\forgotpasswordmailtest' => '/unit/Mails/ForgotPasswordMailTest.php',
                'ganked\\post\\mails\\verifymailtest' => '/unit/Mails/VerifyMailTest.php',
                'ganked\\post\\queries\\fetchaccountquerytest' => '/unit/Queries/FetchAccountQueryTest.php',
                'ganked\\post\\queries\\hasbetarequestquerytest' => '/unit/Queries/HasBetaRequestQueryTest.php',
                'ganked\\post\\queries\\isverifiedforbetaquerytest' => '/unit/Queries/IsVerifiedForBetaQueryTest.php',
                'ganked\\post\\routers\\genericroutertesthelper' => '/unit/Routers/GenericRouterTestHelper.php',
                'ganked\\post\\routers\\postrequestroutertest' => '/unit/Routers/PostRequestRouterTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
