<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\library\\backends\\dombackendtest' => '/Backends/DomBackendTest.php',
                'ganked\\library\\backends\\filebackendtest' => '/Backends/FileBackendTest.php',
                'ganked\\library\\curl\\curltest' => '/Curl/CurlTest.php',
                'ganked\\library\\curl\\responsetest' => '/Curl/ResponseTest.php',
                'ganked\\library\\dataobjects\\accounts\\registeredaccounttest' => '/RegisteredAccountTest.php',
                'ganked\\library\\datapool\\datapoolreadertest' => '/DataPool/DataPoolReaderTest.php',
                'ganked\\library\\datapool\\datapoolwritertest' => '/DataPool/DataPoolWriterTest.php',
                'ganked\\library\\datapool\\leagueoflegendsdatapoolreadertest' => '/DataPool/LeagueOfLegends/LeagueOfLegendsDataPoolReaderTest.php',
                'ganked\\library\\datapool\\leagueoflegendsdatapoolwritertest' => '/DataPool/LeagueOfLegends/LeagueOfLegendsDataPoolWriterTest.php',
                'ganked\\library\\datapool\\redisbackendtest' => '/DataPool/RedisBackendTest.php',
                'ganked\\library\\gateways\\gankedapigatewaytest' => '/Gateways/GankedApiGatewayTest.php',
                'ganked\\library\\generators\\urigeneratortest' => '/Generators/UriGeneratorTest.php',
                'ganked\\library\\helpers\\domhelpertest' => '/Helpers/DomHelperTest.php',
                'ganked\\library\\logging\\loggers\\slackloggertest' => '/Logging/Loggers/SlackLoggerTest.php',
                'ganked\\library\\logging\\loggertest' => '/Logging/LoggerTest.php',
                'ganked\\library\\valueobjects\\dataversiontest' => '/ValueObjects/DataVersionTest.php',
                'ganked\\library\\valueobjects\\emailtest' => '/ValueObjects/EmailTest.php',
                'ganked\\library\\valueobjects\\firstnametest' => '/ValueObjects/FirstNameTest.php',
                'ganked\\library\\valueobjects\\hashtest' => '/ValueObjects/HashTest.php',
                'ganked\\library\\valueobjects\\kdatest' => '/ValueObjects/KDATest.php',
                'ganked\\library\\valueobjects\\lastnametest' => '/ValueObjects/LastNameTest.php',
                'ganked\\library\\valueobjects\\leagueoflegends\\regiontest' => '/ValueObjects/LeagueOfLegends/RegionTest.php',
                'ganked\\library\\valueobjects\\leagueoflegends\\summonernametest' => '/ValueObjects/LeagueOfLegends/SummonerNameTest.php',
                'ganked\\library\\valueobjects\\maptest' => '/ValueObjects/LeagueOfLegends/MapTest.php',
                'ganked\\library\\valueobjects\\metatagstest' => '/ValueObjects/MetaTagsTest.php',
                'ganked\\library\\valueobjects\\passwordtest' => '/ValueObjects/PasswordTest.php',
                'ganked\\library\\valueobjects\\salttest' => '/ValueObjects/SaltTest.php',
                'ganked\\library\\valueobjects\\statisticnumbertest' => '/ValueObjects/StatisticNumberTest.php',
                'ganked\\library\\valueobjects\\tokentest' => '/ValueObjects/TokenTest.php',
                'ganked\\library\\valueobjects\\uritest' => '/ValueObjects/UriTest.php',
                'ganked\\library\\valueobjects\\usernametest' => '/ValueObjects/UsernameTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
