<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\library\\backends\\dombackend' => '/Backends/DomBackend.php',
                'ganked\\library\\backends\\filebackend' => '/Backends/FileBackend.php',
                'ganked\\library\\backends\\mongodatabasebackend' => '/Backends/MongoDatabaseBackend.php',
                'ganked\\library\\cache\\cache' => '/Cache/Cache.php',
                'ganked\\library\\curl\\curl' => '/Curl/Curl.php',
                'ganked\\library\\curl\\curlhandler' => '/Curl/CurlHandler.php',
                'ganked\\library\\curl\\curlmultihandler' => '/Curl/CurlMultiHandler.php',
                'ganked\\library\\curl\\response' => '/Curl/Response.php',
                'ganked\\library\\dataobjects\\accounts\\accountinterface' => '/DataObjects/Accounts/AccountInterface.php',
                'ganked\\library\\dataobjects\\accounts\\anonymousaccount' => '/DataObjects/Accounts/AnonymousAccount.php',
                'ganked\\library\\dataobjects\\accounts\\registeredaccount' => '/DataObjects/Accounts/RegisteredAccount.php',
                'ganked\\library\\datapool\\abstractdatapool' => '/DataPool/AbstractDataPool.php',
                'ganked\\library\\datapool\\datapoolreader' => '/DataPool/DataPoolReader.php',
                'ganked\\library\\datapool\\datapoolwriter' => '/DataPool/DataPoolWriter.php',
                'ganked\\library\\datapool\\leagueoflegendsdatapoolreader' => '/DataPool/LeagueOfLegends/LeagueOfLegendsDataPoolReader.php',
                'ganked\\library\\datapool\\leagueoflegendsdatapoolwriter' => '/DataPool/LeagueOfLegends/LeagueOfLegendsDataPoolWriter.php',
                'ganked\\library\\datapool\\redisbackend' => '/DataPool/RedisBackend.php',
                'ganked\\library\\datapool\\storageinterface' => '/DataPool/StorageInterface.php',
                'ganked\\library\\gateways\\abstractapigateway' => '/Gateways/AbstractApiGateway.php',
                'ganked\\library\\gateways\\favouritesgateway' => '/Gateways/FavouritesGateway.php',
                'ganked\\library\\gateways\\gankedapigateway' => '/Gateways/GankedApiGateway.php',
                'ganked\\library\\generators\\imageurigenerator' => '/Generators/ImageUriGenerator.php',
                'ganked\\library\\generators\\urigenerator' => '/Generators/UriGenerator.php',
                'ganked\\library\\helpers\\domhelper' => '/Helpers/DomHelper.php',
                'ganked\\library\\logging\\logger' => '/Logging/Logger.php',
                'ganked\\library\\logging\\loggeraware' => '/Logging/LoggerAware.php',
                'ganked\\library\\logging\\loggers\\abstractlogger' => '/Logging/Loggers/AbstractLogger.php',
                'ganked\\library\\logging\\loggers\\errorlogger' => '/Logging/Loggers/ErrorLogger.php',
                'ganked\\library\\logging\\loggers\\loggerinterface' => '/Logging/Loggers/LoggerInterface.php',
                'ganked\\library\\logging\\loggers\\slacklogger' => '/Logging/Loggers/SlackLogger.php',
                'ganked\\library\\logging\\logprovider' => '/Logging/LogProvider.php',
                'ganked\\library\\logging\\logs\\criticalexceptionlog' => '/Logging/Logs/CriticalExceptionLog.php',
                'ganked\\library\\logging\\logs\\emergencyexceptionlog' => '/Logging/Logs/EmergencyExceptionLog.php',
                'ganked\\library\\logging\\logs\\loginterface' => '/Logging/Logs/LogInterface.php',
                'ganked\\library\\valueobjects\\cookie' => '/ValueObjects/Cookie.php',
                'ganked\\library\\valueobjects\\dataversion' => '/ValueObjects/DataVersion.php',
                'ganked\\library\\valueobjects\\email' => '/ValueObjects/Email.php',
                'ganked\\library\\valueobjects\\firstname' => '/ValueObjects/FirstName.php',
                'ganked\\library\\valueobjects\\hash' => '/ValueObjects/Hash.php',
                'ganked\\library\\valueobjects\\kda' => '/ValueObjects/KDA.php',
                'ganked\\library\\valueobjects\\lastname' => '/ValueObjects/LastName.php',
                'ganked\\library\\valueobjects\\leagueoflegends\\region' => '/ValueObjects/LeagueOfLegends/Region.php',
                'ganked\\library\\valueobjects\\leagueoflegends\\summonername' => '/ValueObjects/LeagueOfLegends/SummonerName.php',
                'ganked\\library\\valueobjects\\map' => '/ValueObjects/LeagueOfLegends/Map.php',
                'ganked\\library\\valueobjects\\metatags' => '/ValueObjects/MetaTags.php',
                'ganked\\library\\valueobjects\\name' => '/ValueObjects/Name.php',
                'ganked\\library\\valueobjects\\password' => '/ValueObjects/Password.php',
                'ganked\\library\\valueobjects\\post' => '/ValueObjects/Post.php',
                'ganked\\library\\valueobjects\\salt' => '/ValueObjects/Salt.php',
                'ganked\\library\\valueobjects\\statisticnumber' => '/ValueObjects/StatisticNumber.php',
                'ganked\\library\\valueobjects\\steam\\steamcustomid' => '/ValueObjects/Steam/SteamCustomId.php',
                'ganked\\library\\valueobjects\\steam\\steamid' => '/ValueObjects/Steam/SteamId.php',
                'ganked\\library\\valueobjects\\token' => '/ValueObjects/Token.php',
                'ganked\\library\\valueobjects\\uploadedfile' => '/ValueObjects/UploadedFile.php',
                'ganked\\library\\valueobjects\\uri' => '/ValueObjects/Uri.php',
                'ganked\\library\\valueobjects\\userid' => '/ValueObjects/UserId.php',
                'ganked\\library\\valueobjects\\username' => '/ValueObjects/Username.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
