<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\backend\\builders\\staticpagebuildertest' => '/unit/Builders/StaticPageBuilderTest.php',
                'ganked\\backend\\controllertest' => '/unit/ControllerTest.php',
                'ganked\\backend\\factories\\backendfactorytest' => '/unit/Factories/BackendFactoryTest.php',
                'ganked\\backend\\factories\\builderfactorytest' => '/unit/Factories/BuilderFactoryTest.php',
                'ganked\\backend\\factories\\genericfactorytesthelper' => '/unit/Factories/GenericFactoryTestHelper.php',
                'ganked\\backend\\factories\\locatorfactorytest' => '/unit/Factories/LocatorFactoryTest.php',
                'ganked\\backend\\factories\\mapperfactorytest' => '/unit/Factories/MapperFactoryTest.php',
                'ganked\\backend\\factories\\taskfactorytest' => '/unit/Factories/TaskFactoryTest.php',
                'ganked\\backend\\factories\\writerfactorytest' => '/unit/Factories/WriterFactoryTest.php',
                'ganked\\backend\\locators\\tasklocatortest' => '/unit/Locators/TaskLocatorTest.php',
                'ganked\\backend\\mappers\\leagueoflegendsleaderboardmappertest' => '/unit/Mappers/LeagueOfLegendsLeaderboardMapperTest.php',
                'ganked\\backend\\requesttest' => '/unit/RequestTest.php',
                'ganked\\backend\\tasks\\buildchampionpagestasktest' => '/unit/Tasks/BuildChampionPagesTaskTest.php',
                'ganked\\backend\\tasks\\buildstaticpagetasktest' => '/unit/Tasks/BuildStaticPageTaskTest.php',
                'ganked\\backend\\tasks\\initialtasktest' => '/unit/Tasks/InitialTaskTest.php',
                'ganked\\backend\\tasks\\leagueoflegendschallengerleaderboardsgettasktest' => '/unit/Tasks/Get/LeagueOfLegends/LeagueOfLegendsChallengerLeaderboardsGetTaskTest.php',
                'ganked\\backend\\tasks\\leagueoflegendscurrentpatchgettasktest' => '/unit/Tasks/Get/LeagueOfLegends/LeagueOfLegendsCurrentPatchGetTaskTest.php',
                'ganked\\backend\\tasks\\leagueoflegendsfreechampionspushtasktest' => '/unit/Tasks/Push/LeagueOfLegendsFreeChampionsPushTaskTest.php',
                'ganked\\backend\\tasks\\leagueoflegendsmasterleaderboardsgettasktest' => '/unit/Tasks/Get/LeagueOfLegends/LeagueOfLegendsMasterLeaderboardsGetTaskTest.php',
                'ganked\\backend\\writers\\leagueoflegendsleaderboardwritertest' => '/unit/Writers/LeagueOfLegendsLeaderboardWriterTest.php',
                'ganked\\backend\\writers\\staticpagewritertest' => '/unit/Writers/StaticPageWriterTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
