<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\services\\backends\\slackbackendtest' => '/Backends/SlackBackendTest.php',
                'ganked\\services\\factories\\backendfactorytest' => '/Factories/BackendFactoryTest.php',
                'ganked\\services\\factories\\controllerfactorytest' => '/Factories/ControllerFactoryTest.php',
                'ganked\\services\\factories\\genericfactorytesthelper' => '/Factories/GenericFactoryTestHelper.php',
                'ganked\\services\\factories\\routerfactorytest' => '/Factories/RouterFactoryTest.php',
                'ganked\\services\\factories\\serviceclientfactorytest' => '/Factories/ServiceClientFactoryTest.php',
                'ganked\\services\\serviceclients\\account\\accountserviceclienttest' => '/ServiceClients/Account/AccountServiceClientTest.php',
                'ganked\\services\\serviceclients\\api\\counterstrikeserviceclienttest' => '/ServiceClients/API/Steam/CounterStrikeAPIServiceClientTest.php',
                'ganked\\services\\serviceclients\\api\\lolserviceclienttest' => '/ServiceClients/API/LoLServiceClientTest.php',
                'ganked\\services\\serviceclients\\api\\twitchserviceclienttest' => '/ServiceClients/API/TwitchServiceClientTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
