<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'ganked\\frontend\\commands\\savedefaultleagueoflegendsregioninsessioncommandtest' => '/unit/Commands/SaveDefaultLeagueOfLegendsRegionInSessionCommandTest.php',
                'ganked\\frontend\\controllers\\passwordrecoverypagecontrollertest' => '/unit/Controllers/PageControllers/PasswordRecoveryPageControllerTest.php',
                'ganked\\frontend\\controllers\\redirectcontrollertest' => '/unit/Controllers/RedirectControllerTest.php',
                'ganked\\frontend\\controllers\\searchpagecontrollertest' => '/unit/Controllers/PageControllers/SearchPageControllerTest.php',
                'ganked\\frontend\\controllers\\staticpagecontrollertest' => '/unit/Controllers/PageControllers/StaticPageControllerTest.php',
                'ganked\\frontend\\dataobjects\\counterstrike\\usertest' => '/unit/DataObjects/CounterStrike/UserTest.php',
                'ganked\\frontend\\dataobjects\\profiletest' => '/unit/DataObjects/ProfileTest.php',
                'ganked\\frontend\\dataobjects\\summonertest' => '/unit/DataObjects/LeagueOfLegends/SummonerTest.php',
                'ganked\\frontend\\factories\\commandfactorytest' => '/unit/Factories/CommandFactoryTest.php',
                'ganked\\frontend\\factories\\controllerfactorytest' => '/unit/Factories/ControllerFactoryTest.php',
                'ganked\\frontend\\factories\\genericfactorytesthelper' => '/unit/Factories/GenericFactoryTestHelper.php',
                'ganked\\frontend\\factories\\handlerfactorytest' => '/unit/Factories/HandlerFactoryTest.php',
                'ganked\\frontend\\factories\\mapperfactorytest' => '/unit/Factories/MapperFactoryTest.php',
                'ganked\\frontend\\factories\\queryfactorytest' => '/unit/Factories/QueryFactoryTest.php',
                'ganked\\frontend\\factories\\readerfactorytest' => '/unit/Factories/ReaderFactoryTest.php',
                'ganked\\frontend\\factories\\rendererfactorytest' => '/unit/Factories/RendererFactoryTest.php',
                'ganked\\frontend\\factories\\routerfactorytest' => '/unit/Factories/RouterFactoryTest.php',
                'ganked\\frontend\\handlers\\leagueoflegendssearchhandlertest' => '/unit/Handlers/LeagueOfLegendsSearchHandlerTest.php',
                'ganked\\frontend\\mappers\\counterstrikeusermappertest' => '/unit/Mappers/CounterStrikeUserMapperTest.php',
                'ganked\\frontend\\mappers\\leagueoflegendsrecentgamesmappertest' => '/unit/Mappers/LeagueOfLegendsRecentGamesMapperTest.php',
                'ganked\\frontend\\mappers\\leagueoflegendssummonermappertest' => '/unit/Mappers/LeagueOfLegendsSummonerMapperTest.php',
                'ganked\\frontend\\mappers\\leagueoflegendssummonerrolemappertest' => '/unit/Mappers/LeagueOfLegendsSummonerRoleMapperTest.php',
                'ganked\\frontend\\models\\redirectmodeltest' => '/unit/Models/RedirectModelTest.php',
                'ganked\\frontend\\models\\staticpagemodeltest' => '/unit/Models/StaticPageModelTest.php',
                'ganked\\frontend\\models\\steamuserpagemodeltest' => '/unit/Models/Steam/SteamUserPageModelTest.php',
                'ganked\\frontend\\models\\summonermasteriespagemodeltest' => '/unit/Models/LeagueOfLegends/SummonerMasteriesPageModelTest.php',
                'ganked\\frontend\\models\\summonerpagemodeltest' => '/unit/Models/LeagueOfLegends/SummonerPageModelTest.php',
                'ganked\\frontend\\models\\summonerrunespagemodeltest' => '/unit/Models/LeagueOfLegends/SummonerRunesPageModelTest.php',
                'ganked\\frontend\\queries\\fetchdefaultleagueoflegendsregionfromsessionquerytest' => '/unit/Queries/LeagueOfLegends/FetchDefaultLeagueOfLegendsRegionFromSessionQueryTest.php',
                'ganked\\frontend\\queries\\fetchsummonersbynamequerytest' => '/unit/Queries/FetchSummonersByNameQueryTest.php',
                'ganked\\frontend\\queries\\hasdefaultleagueoflegendsregionfromsessionquerytest' => '/unit/Queries/LeagueOfLegends/HasDefaultLeagueOfLegendsRegionFromSessionQueryTest.php',
                'ganked\\frontend\\readers\\urlredirectreadertest' => '/unit/Readers/UrlRedirectReaderTest.php',
                'ganked\\frontend\\renderers\\appendcsrftokensnippetrenderertest' => '/unit/Renderers/Snippets/AppendCSRFTokenSnippetRendererTest.php',
                'ganked\\frontend\\renderers\\bargraphrenderertest' => '/unit/Renderers/Snippets/BarGraphRendererTest.php',
                'ganked\\frontend\\renderers\\genericpagerenderertest' => '/unit/Renderers/Pages/GenericPageRendererTest.php',
                'ganked\\frontend\\renderers\\infobarrenderertest' => '/unit/Renderers/Snippets/InfoBarRendererTest.php',
                'ganked\\frontend\\renderers\\metatagssnippetsrenderertest' => '/unit/Renderers/Snippets/MetaTagsSnippetsRendererTest.php',
                'ganked\\frontend\\renderers\\signinlinkssnippetrenderertest' => '/unit/Renderers/Snippets/SignInLinksSnippetRendererTest.php',
                'ganked\\frontend\\renderers\\staticpagerenderertest' => '/unit/Renderers/Pages/StaticPageRendererTest.php',
                'ganked\\frontend\\renderers\\trackingsnippetrenderertest' => '/unit/Renderers/Snippets/TrackingSnippetRendererTest.php',
                'ganked\\frontend\\routers\\accountpageroutertest' => '/unit/Routers/AccountPageRouterTest.php',
                'ganked\\frontend\\routers\\counterstrikepageroutertest' => '/unit/Routers/CounterStrikePageRouterTest.php',
                'ganked\\frontend\\routers\\errorpageroutertest' => '/unit/Routers/ErrorPageRouterTest.php',
                'ganked\\frontend\\routers\\genericroutertesthelper' => '/unit/Routers/GenericRouterTestHelper.php',
                'ganked\\frontend\\routers\\leagueoflegendspageroutertest' => '/unit/Routers/LeagueOfLegendsPageRouterTest.php',
                'ganked\\frontend\\routers\\redirectroutertest' => '/unit/Routers/RedirectRouterTest.php',
                'ganked\\frontend\\routers\\searchpageroutertest' => '/unit/Routers/SearchPageRouterTest.php',
                'ganked\\frontend\\routers\\staticpageroutertest' => '/unit/Routers/StaticPageRouterTest.php',
                'ganked\\frontend\\unit\\models\\searchpagemodeltest' => '/unit/Models/SearchPageModelTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
